# Generated by Django 5.0.7 on 2024-08-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Programmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("dob", models.CharField(max_length=20)),
                ("language", models.CharField(max_length=20)),
                ("quote", models.CharField(max_length=150)),
            ],
        ),
    ]
