services:
  db:
    image: postgres:14-alpine
    container_name: db

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=manage-api

    volumes:
      - postgresql:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7.0.5-alpine

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /manage-api/frontend
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

    ports:
      - "3000:3000"

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    container_name: backend

    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend
        - action: rebuild
          path: requirements.txt

    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"

    depends_on:
      - db

  worker:
    restart: unless-stopped
    command: celery -A api worker -l info
    container_name: worker-celery
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=manage-api
      - POSTGRES_PORT=5432
    depends_on:
      - db
      - redis

volumes:
  node_modules:
    driver: local
  postgresql:
    driver: local
  pgadmin-data:
    driver: local
